### ISSUE TITLE
라이센스가 어떻게 되나요?

### ISSUE THREAD

**Issue by MoorDev** [k2webtech/hwp2odt#1]
굉장히 마음에드는 플러그인입니다.
LibreOffice에서 hwp를 읽을 수있는 것만으로도 편리하네요.
이런건 모두에게 알려야한다고 생각합니다.

그런데 이 플러그인을 리브레오피스와 함께 리눅스 배포판에 같이 포함해서 배포해도 되는지 궁금합니다.

**Comment by k2webtech** [comment]
저희는 리눅스 배포판에 이 extension을 어떻게 포함시키는지는 알지 못합니다만,
공개하는 목적에 부합하는 만큼,  리눅스 배포판에 포함되어도 됩니다.
Hwp2Odt 사용을 유료화하지 않을것이나,  제작자는 케이투웹테크(주) 임을 명시해 주시면 됩니다.
