### ISSUE TITLE
hwp2odt 배포 방안 제안

### ISSUE THREAD

**Issue by OctopusET** [k2webtech/hwp2odt#2]
안녕하세요 배포 방안을 몇가지 제안 드립니다.

https://github.com/github-release/github-release/releases
위와 같이 Github 내장 기능 Release를 활용하여 배포가 된다면 여러가지 장점이 있을 수 있습니다.
- 매번 release 때마다 알림 받기 가능
- 구버전을 다운 받기 수월합니다.
- 버전 수정 사항을 확인 하기 더욱 수월합니다.

공식 libreoffice extension 사이트 https://extensions.libreoffice.org/en/home/
[(혹은 OpenOffice)](https://extensions.openoffice.org/)
위 사이트에서 hwp2odt를 바로 다운 받을 수 있다면 더욱 편리 할 듯 합니다. 

확인 해본결과 확장 프로그램을 등록할 때 라이선스 선택창에서 GPL등 과 같은 FOSS 라이선스 이외에도 Proprietary License 가 선택 가능하므로 개발사에서 이를 선택하는 것도 가능하겠습니다.

확장 프로그램 등록 예시: https://extensions.libreoffice.org/en/extensions/show/korean-spellchecker)
확장 프로그램 공식 사이트 등록/관리 메뉴얼: https://extensions.libreoffice.org/en/home/using-this-site-as-an-extension-maintainer/

감사합니다.

**Comment by k2webtech** [comment]
제안해 주신 대로 배포해보니  장점을 확인하게 되네요. 
앞으로는 이 방식으로 배포를 하겠습니다.
공식 extension 사이트에도 등록했습니다만,  매번 릴리스는 아니고 major 버전마다 올리려고 합니다. 

조언 감사합니다.

**Comment by OctopusET** [comment]
@k2webtech 적용 감사드립니다
