### ISSUE TITLE
일부 hwp 파일들은 열어도 내용이 표시가 되지 않습니다.

### ISSUE THREAD

**Issue by schaats** [k2webtech/hwp2odt#3]
안녕하세요, 
고생하시며 개발 하고 이렇게 공개 하여 주셔서 감사하게 잘 사용 하고 있는 사용자 입니다.
다름이 아니라, 특정 HWP 파일 들에 대해서는 아무런 내용도 표시 하여 주지 않는 현상이 있어서 입니다.
첨부한 zip 파일 내의 hwp 파일 들은 HWP 로 열었을 때에는 정상적으로 내용 표시가 되는데, Libreoffice 와 hwp2odt 에서는 문서를 열면 마치 '새로 만들기' 등으로 열었을 때 처럼 아무런 내용이 표시가 되지 않습니다.
테스트 하였던 환경은 아래와 같습니다.

OS : openSUSE tumbleweed, openSUSE leap 15.3.1 , 
Libreoffice version :  7.2.5.1,  7.1.4.2
hwp2odt : 0.36, 0.37

상기 환경의 다양한 조함에서 모두 결과는 동일 하였습니다.
감사합니다.
[hwp.zip](https://github.com/k2webtech/hwp2odt/files/7949672/hwp.zip)

**Comment by k2webtech** [comment]
이슈 리포트 감사합니다.
한컴문서 기준으로 제작하다보니   오래전 Hwp버전에서 제작된 문서 처리가 미흡합니다.
제공해주신 파일이  우선 변환되도록 했으며,  문서 내용의 변환 품질이 낮은 부분은 지속적으로 개선하겠습니다.
변환 품질이 부족한 부분 중  별도로 이슈 리포트 주시면 , 그 부분을 먼저 살펴보겠습니다.
금번 수정내용이 적용된 버전은  v0.3.8 입니다.
감사합니다.

**Comment by schaats** [comment]
빠른 조치에 진심으로 감사드립니다.
