### ISSUE TITLE
일부 hwp 파일의 내용이 정상적으로 표시 되지 않습니다.

### ISSUE THREAD

**Issue by schaats** [k2webtech/hwp2odt#4]
안녕하세요, 항상 감사한 마음으로 사용 하고 있는 사용자 입니다.
지난번에 이어 두번 째 버그 리포팅을 합니다.
첨부한 hwp 파일의 내용이 정상적으로 표시 되지 않는 현상을 발견 하게 되어 리포팅 합니다.
각 페이지의 내용이 밀려 출력 되며 하단부가 잘려 정상 출력이 되지 않습니다.
 
hwp 문서 버전 : 5.1.0.1.1

테스트 환경
OS : openSUSE tumbleweed, openSUSE leap 15.3.2 ,
Libreoffice version : 7.3.1.3, 7.1.4.2
hwp2odt : 0.38, 0.40
[2022학급편성결과(1학년)-홈페이지게시용.zip](https://github.com/k2webtech/hwp2odt/files/8239958/2022.1.-.zip)

**Comment by k2webtech** [comment]
안녕하세요.  이슈 리포팅 감사합니다. 

한컴과  리브레오피스의 테이블 속성이 달라,  유사하게 표현하도록 하는데 시간이 좀 걸렸습니다.
해당 이슈를 수정하여  v0.4.1 버전을 배포합니다. 

감사합니다.

**Comment by schaats** [comment]
항상 빠른 조치에 진심으로 감사 드립니다.
