### ISSUE TITLE
특정 hwp 파일 열면 죽는 현상이 발생합니다.

### ISSUE THREAD

**Issue by kevin747** [k2webtech/hwp2odt#5]
[2015-1 침대도면.zip](https://github.com/k2webtech/hwp2odt/files/8579287/2015-1.zip)

안녕하세요,
좋은 프로그램을 공개해 주셔서 감사합니다.
첨부한 hwp 파일을 열면 죽는 현상이 발생합니다.

테스트 환경
OS : Ubuntu 18.04
Libreoffice version : 7.3.2.2
hwp2odt : 0.4.2

**Comment by k2webtech** [comment]
안녕하세요. 

아래 세부 사항은  개발자가 아니면  이해하기 어려울 수도 있으나,  
본 이슈를 보는 다른 개발자 분이 계시다면  도움을 받을 수 있을 수도 있어서  내용을 적습니다.

hwp파일에서 묶음 개체를 읽어내는 중에   읽지 못한 부분이 있어 죽는 현상이 발생하는 걸로 확인했습니다.
죽는 현상이 없도록  빠른 수정은 할 수 있습니다만,
OLE개체, 차트개체, 묶음 개체 등를 읽어내서 해석하는 부분이 한컴 문서에 자세히 나와있지 않아서
묶음 개체를 읽어내더라도  화면에 제대로 표현할 수 없는 상태입니다.  
개체 위치, 회전 등  제대로 계산이 안되어  엉뚱하게 그려집니다.

제공해주신 hwp 파일에서  묶음개체 내 있는 개체들의  traslation matrix, scale matrix, rotation matrix 를 해석하는 방법을 몰라 개선을 하지 못하는 상태입니다.
한글문서파일형식 문서 경로:  https://www.hancom.com/etc/hwpDownload.do
예 )
translation matrix =
[ 1, 0, 3402
  0,  1,  -3401
  0,  0,  1]
scale matrix  =
[ 1.79,  0, -1417
  0,  9.25,  0 
  0, 0, 1 ]
rotation matrix = 
[ 0, 1, -3402
  -1, 0, 5102
  0, 0, 1 ]
한컴 문서에는  어떻게 해석해야 하는지에 대한 내용이 없고,  이마저도  ranslation matrix,  scale matrix, rotration matrix 라고 적혀있습니다. 

좀 더 시간을 두고 파악하려고 합니다.  

혹여나  3가지 matrix 에 대해 어떻게 해석해야 하는지 아시는 분은  내용 남겨주시면  감사합니다.

감사합니다.

**Comment by OctopusET** [comment]
@k2webtech 
https://github.com/neolord0/hwplib/tree/master/src/main/java/kr/dogfoot/hwplib/object/bodytext/control/gso/shapecomponent/renderingnfo

이 디렉토리의 소스들이 matrix 관련 처리를 하는 부분 같습니다.

**Comment by k2webtech** [comment]
@OctopusET 
우선 시간내어 찾아봐주시고 알려주셔서 감사합니다. 
링크의 내용을 봤습니다만,  matrix를  문서내에서 읽어내는 부분에 한정된 것 같습니다. 
읽어낸 matrix 값들과 원래의 좌표값을 해석(계산)하여,   변환된 좌표(화면에 그릴 좌표)를 구하는  방법이 필요한데요.
예로 적은 것 처럼  hwp에서 읽어낸 matrix 값들이 워낙 범위가 넓어,  2D AffineTransform 으로 해석할 엄두를 내지 못하고 있습니다.

**Comment by k2webtech** [comment]
중복 묶음 개체 처리에서 문제가 된 부분을 수정하여 죽는 현상을 수정했습니다.
matrix 연산은  2D affine transform 을 참조하여  일부 개선하였습니다.  아래의 자료를 참고하였습니다.
https://en.wikipedia.org/wiki/Transformation_matrix#/media/File:2D_affine_transformation_matrix.svg

그러나  묶음 개체내  offset 값을 계산하는 방법은 알아내지 못해  개체들이 엉뚱한 위치에 그려집니다.
이 내용은  단 시간내에  개선할 수 없을것 같아서,  수정한 내용 만을 적용하여 새 버전을 배포합니다.
개체를 맞는 위치에 그리도록 수정할 때까지,  본 이슈는 닫지 않고  open 상태를 유지하겠습니다.

감사합니다.

**Comment by k2webtech** [comment]
transform matrix 연산에 대한 부분을 찾았습니다.
http://www.opengl-tutorial.org/beginners-tutorials/tutorial-3-matrices/
매트릭스 연산식은 아래와 같구요.
TransformedVector = TranslationMatrix * RotationMatrix * ScaleMatrix * OriginalVector;
매트릭스 연산은 오른쪽부터 왼쪽으로 하나씩 연산하고, 순서가 달라지면 값이 달라지니 주의하라고 하네요.

한컴문서내에서 묶음개체가 여러(N)번 묶여 있는 경우가 있으니, 아래와 같은 과정을 거쳐야 하겠습니다.
TransformedVector = TranslationMatrix * RotationMatrix(1) * ScaleMatrix(1) * ... * RotationMatrix(N-1) * ScaleMatrix(N-1)* RotationMatrix(N) * ScaleMatrix(N) * OriginalVector;

엑셀에 넣고 계산해보니 값이 맞게 나오는것 같아서, 수정이 가능할것 같습니다.
이 방식으로 처리해보겠습니다.

**Comment by k2webtech** [comment]
v0.4.4 에 수정내용 적용되었습니다. 
한컴은   페이지를 벗어난 개체도  transform 하는 반면,  
리브레오피스는  페이지를 벗어난 개체는  페이지 내로 강제로 이동시켜 그리는 제약 때문에  동일수준으로 변환되지는 않습니다.
제약을 넘기가 어려워  현재 수준으로  close 합니다.
