### ISSUE TITLE
hwp 파일을 열면 내용이 1 이라고만 표시 됩니다.

### ISSUE THREAD

**Issue by dhkim-2001** [k2webtech/hwp2odt#6]
[8.25-2023년도.zip](https://github.com/k2webtech/hwp2odt/files/9474851/8.25-2023.zip)

안녕하세요, 공개해 주신 프로그램 감사히 잘 사용하는 사용자중 한명입니다.
최근 첨부된 한글 파일을 열었을때 내용이 1 이라고만 나오는
현상이 발생하고 있습니다.

테스트 환경은 아래와 같습니다.
OS : CentOS 7.9
Libreoffice version : 7.2.7.2
hwp2odt : 0.4.4

**Comment by k2webtech** [comment]
안녕하세요.  
이슈 리포트를 주셨는데,  개선하는데 시간이 오래 지체 되었습니다.  
리포트 주신 내용을 수정하여  v0.4.5 버전을 배포하였습니다.
감사합니다.
