### ISSUE TITLE
Table style is incorrectly

### ISSUE THREAD

**Issue by realx94** [k2webtech/hwp2odt#7]
Hi @k2webtech, 
I try to open an HWP file but the table style does not show exactly. Could you check the problem and fix it.
HWP File: [tests.zip](https://github.com/k2webtech/hwp2odt/files/9906880/tests.zip)
File show in handcom viewer: ![image](https://user-images.githubusercontent.com/12102840/199159613-0cfb5ee7-dced-4bf3-a4ac-f3ac6fbfc923.png)
File show in LibreOffice: ![image](https://user-images.githubusercontent.com/12102840/199159699-76f771cf-7575-45d6-b2bd-47010a74cc40.png)

Your extension is perfect. I appreciate your project.

**Comment by k2webtech** [comment]
Hello realx94,
Thank you for your reporting an issue.
I have looked into this issue and reached out the the conclusion that LibreOffice table seems not allow 0 width column.
So I made a change that table column have at least 1 value width even if the column is not visible.
Please check newer extension which version is v.0.4.6. 
Thank you.

**Comment by realx94** [comment]
@k2webtech It's work. Thank you so much! 
I will close the issue.
